name: CI

on:
  push:
    branches:
      - main
      - "*.*.x"
    tags:
      - '*'
  pull_request:
  schedule:
    # Weekly Monday 9AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 9 * * 1'
  workflow_dispatch:


jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: check-style
        - linux: build-dist
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: test-oldestdeps-cov
          python-version: 3.9
        - linux: test
          python-version: 3.9
        - linux: test
          python-version: 3.10
        - linux: test
          python-version: 3.11
        - macos: test
          python-version: 3.11
        - linux: test-cov
          coverage: codecov
  test_upstream:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: test-rad
